version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: milkrun_sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Logistica@2025!
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  redis:
    image: redis:alpine
    container_name: milkrun_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  sql_data:
  redis_data: